// <auto-generated />
namespace MercadinhoClass.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AlteraçãoNomeCampoProduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlteraçãoNomeCampoProduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201911021226429_Alteração Nome Campo Produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
