// <auto-generated />
namespace MercadinhoClass.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Criado_Tab_Estoque : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criado_Tab_Estoque));
        
        string IMigrationMetadata.Id
        {
            get { return "201911050052061_Criado_Tab_Estoque"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
