// <auto-generated />
namespace MercadinhoClass.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Venda_ValorVenda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Venda_ValorVenda));
        
        string IMigrationMetadata.Id
        {
            get { return "201911091203196_Venda_ValorVenda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
