// <auto-generated />
namespace MercadinhoClass.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Estoque_Campo_EstoqueAtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Estoque_Campo_EstoqueAtual));
        
        string IMigrationMetadata.Id
        {
            get { return "201911081738224_Estoque_Campo_EstoqueAtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
