// <auto-generated />
namespace Projeto2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class valor_padrao_Conta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(valor_padrao_Conta));
        
        string IMigrationMetadata.Id
        {
            get { return "201910142329504_valor_padrao_Conta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
